bash tools/dist_train.sh local_configs/cg/logits_cg15.py 8
bash tools/dist_train.sh local_configs/cg/logits_cg6.py 8
bash tools/dist_train.sh local_configs/cg/logits_cg10.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=1_w=0.2.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_es_80k.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_es_112k.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_es_96k.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=1_w=2.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=1_w=0.5.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_es_144k.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=0.5_w=1.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=2_w=1.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=1_w=4.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=16_w=1.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=4_w=1.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_T=8_w=1.py 8
bash tools/dist_train.sh local_configs/cg5_grid/logits_cg5_es_128k.py 8
bash tools/dist_train.sh local_configs/10.14/logtis_cg5_shift.py 8
bash tools/dist_train.sh local_configs/10.14/logtis_cg5_shuffle.py 8
bash tools/dist_train.sh local_configs/10.14/feature_es_96k.py 8
bash tools/dist_train.sh local_configs/qkv_stage1/k_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage1/q_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage1/v_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage1/q_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage1/v_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage1/k_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage2/k_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage2/q_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage2/v_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage2/q_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage2/v_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage2/k_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage3/k_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage3/q_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage3/v_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage3/q_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage3/v_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage3/k_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage4/k_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage4/q_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage4/v_c.py 8
bash tools/dist_train.sh local_configs/qkv_stage4/q_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage4/v_cg4.py 8
bash tools/dist_train.sh local_configs/qkv_stage4/k_c.py 8
bash tools/dist_train.sh local_configs/sg/logits_sg32_16.py 8
bash tools/dist_train.sh local_configs/sg/logits_sg128_64.py 8
bash tools/dist_train.sh local_configs/sg/logits_sg64_32.py 8
bash tools/dist_train.sh local_configs/sg/logits_sg16_8.py 8
