bash tools/dist_train.sh local_configs/multi-teacher/A4-2-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A4-1-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F4-1-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A1-2-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A4-2-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F1-2-2.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F4-2-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F1-2-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A1-2-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A1-1-2.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F1-1-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A4-2-2.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A4-1-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F4-2-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F4-2-2.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A4-1-2.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F4-1-2.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F1-2-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F1-1-2.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A1-1-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F4-1-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A1-1-1.py 8
bash tools/dist_train.sh local_configs/multi-teacher/F1-1-3.py 8
bash tools/dist_train.sh local_configs/multi-teacher/A1-2-2.py 8