bash tools/dist_train.sh local_configs/distill_seg/baseline.py 2;
sleep 10s;
bash tools/dist_train.sh local_configs/distill_seg/logits_mpl_attn.py 2;
sleep 10s;
bash tools/dist_train.sh local_configs/distill_seg/attn.py 2;
sleep 10s;
bash tools/dist_train.sh local_configs/distill_seg/mlp.py 2;
sleep 10s;
bash tools/dist_train.sh local_configs/distill_seg/logits.py 2;
sleep 10s;